# Generated by Django 4.1.7 on 2023-04-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=5)),
                ('image', models.ImageField(default='default_image.jpg', upload_to='category_images')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
