# Generated by Django 4.1.7 on 2023-04-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_price_alter_product_name_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_image.jpg', upload_to='category_images')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Bottel', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='plastil', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(default='sport', max_length=50),
        ),
    ]
